### ISSUE TITLE
How to connect nodes?

### ISSUE THREAD

**Issue by shujaatak** [maxjoehnk/Mizer#14]
Is there a way to connect nodes inputs and outputs yet?

**Comment by maxjoehnk** [comment]
You can right click output ports in the ui to connect to compatible input ports.
You can't disconnect nodes at runtime currently.

**Comment by shujaatak** [comment]
I tried my best but I failed to connect ports.

**Comment by maxjoehnk** [comment]
Which nodes have you tried to connect?
This project is very much a work in progress and is not really ready for end users.
