### ISSUE TITLE
Not an issue but can you please mention the reason why you shifted to Tide from Actix-Web?

### ISSUE THREAD

**Issue by shujaatak** [maxjoehnk/Mizer#15]
I really like them both but I am highly interested in knowing why people choose one over another.

**Comment by maxjoehnk** [comment]
I want to get rid of tokio. That's the only reason but it also has the benefit of faster compiles and it being a smaller crate.

**Comment by shujaatak** [comment]
If you don't mind, can you please tell why did you want to get rid of tokio?

**Comment by maxjoehnk** [comment]
For two reasons:
The current version of tokio used in this project is kinda old but many libraries still depend on it so I had to stick with it.
The grpc api still depends on it and this will probably stay this way for now. But I would like to keep most of the code runtime agnostic so I can be more flexible with the way I configure the task executor.
I will probably introduce smol as a runtime in the near future so I can run the main loop on a thread local executor but run background jobs on a multi threaded executor.

**Comment by shujaatak** [comment]
Thank you so much for such a great explanation! You are wonderful!
