### ISSUE TITLE
Is Mizer ISF shader capable?

### ISSUE THREAD

**Issue by xmoov** [maxjoehnk/mizer#250]
Can Mizer run ISF shaders?

**Comment by maxjoehnk** [comment]
Sadly the video aspect of Mizer is currently very much in a prototype phase and it can't run proper video pipelines.
So shader support is basically non-existent currently.

I'm planing to use wgpu which should be able to support isf shaders though.

**Comment by maxjoehnk** [comment]
I've created a new issue to track a new ISF Shader node as the video support has come a long way since June.
I'll close this one, if you have any further questions or ideas please refer to #351.
